/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SigningPayload from './SigningPayload';

/**
 * The ConstructionPayloadsResponse model module.
 * @module model/ConstructionPayloadsResponse
 * @version 1.4.10
 */
class ConstructionPayloadsResponse {
    /**
     * Constructs a new <code>ConstructionPayloadsResponse</code>.
     * ConstructionTransactionResponse is returned by &#x60;/construction/payloads&#x60;. It contains an unsigned transaction blob (that is usually needed to construct the a network transaction from a collection of signatures) and an array of payloads that must be signed by the caller.
     * @alias module:model/ConstructionPayloadsResponse
     * @param unsignedTransaction {String} 
     * @param payloads {Array.<module:model/SigningPayload>} 
     */
    constructor(unsignedTransaction, payloads) { 
        
        ConstructionPayloadsResponse.initialize(this, unsignedTransaction, payloads);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, unsignedTransaction, payloads) { 
        obj['unsigned_transaction'] = unsignedTransaction;
        obj['payloads'] = payloads;
    }

    /**
     * Constructs a <code>ConstructionPayloadsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConstructionPayloadsResponse} obj Optional instance to populate.
     * @return {module:model/ConstructionPayloadsResponse} The populated <code>ConstructionPayloadsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConstructionPayloadsResponse();

            if (data.hasOwnProperty('unsigned_transaction')) {
                obj['unsigned_transaction'] = ApiClient.convertToType(data['unsigned_transaction'], 'String');
            }
            if (data.hasOwnProperty('payloads')) {
                obj['payloads'] = ApiClient.convertToType(data['payloads'], [SigningPayload]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} unsigned_transaction
 */
ConstructionPayloadsResponse.prototype['unsigned_transaction'] = undefined;

/**
 * @member {Array.<module:model/SigningPayload>} payloads
 */
ConstructionPayloadsResponse.prototype['payloads'] = undefined;






export default ConstructionPayloadsResponse;

