/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountIdentifier from './AccountIdentifier';
import Amount from './Amount';
import CoinChange from './CoinChange';
import OperationIdentifier from './OperationIdentifier';

/**
 * The Operation model module.
 * @module model/Operation
 * @version 1.4.10
 */
class Operation {
    /**
     * Constructs a new <code>Operation</code>.
     * Operations contain all balance-changing information within a transaction. They are always one-sided (only affect 1 AccountIdentifier) and can succeed or fail independently from a Transaction. Operations are used both to represent on-chain data (Data API) and to construct new transactions (Construction API), creating a standard interface for reading and writing to blockchains.
     * @alias module:model/Operation
     * @param operationIdentifier {module:model/OperationIdentifier} 
     * @param type {String} Type is the network-specific type of the operation. Ensure that any type that can be returned here is also specified in the NetworkOptionsResponse. This can be very useful to downstream consumers that parse all block data.
     */
    constructor(operationIdentifier, type) { 
        
        Operation.initialize(this, operationIdentifier, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operationIdentifier, type) { 
        obj['operation_identifier'] = operationIdentifier;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Operation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Operation} obj Optional instance to populate.
     * @return {module:model/Operation} The populated <code>Operation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Operation();

            if (data.hasOwnProperty('operation_identifier')) {
                obj['operation_identifier'] = OperationIdentifier.constructFromObject(data['operation_identifier']);
            }
            if (data.hasOwnProperty('related_operations')) {
                obj['related_operations'] = ApiClient.convertToType(data['related_operations'], [OperationIdentifier]);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = AccountIdentifier.constructFromObject(data['account']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('coin_change')) {
                obj['coin_change'] = CoinChange.constructFromObject(data['coin_change']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OperationIdentifier} operation_identifier
 */
Operation.prototype['operation_identifier'] = undefined;

/**
 * Restrict referenced related_operations to identifier indices < the current operation_identifier.index. This ensures there exists a clear DAG-structure of relations. Since operations are one-sided, one could imagine relating operations in a single transfer or linking operations in a call tree.
 * @member {Array.<module:model/OperationIdentifier>} related_operations
 */
Operation.prototype['related_operations'] = undefined;

/**
 * Type is the network-specific type of the operation. Ensure that any type that can be returned here is also specified in the NetworkOptionsResponse. This can be very useful to downstream consumers that parse all block data.
 * @member {String} type
 */
Operation.prototype['type'] = undefined;

/**
 * Status is the network-specific status of the operation. Status is not defined on the transaction object because blockchains with smart contracts may have transactions that partially apply (some operations are successful and some are not). Blockchains with atomic transactions (all operations succeed or all operations fail) will have the same status for each operation. On-chain operations (operations retrieved in the `/block` and `/block/transaction` endpoints) MUST have a populated status field (anything on-chain must have succeeded or failed). However, operations provided during transaction construction (often times called \"intent\" in the documentation) MUST NOT have a populated status field (operations yet to be included on-chain have not yet succeeded or failed).
 * @member {String} status
 */
Operation.prototype['status'] = undefined;

/**
 * @member {module:model/AccountIdentifier} account
 */
Operation.prototype['account'] = undefined;

/**
 * @member {module:model/Amount} amount
 */
Operation.prototype['amount'] = undefined;

/**
 * @member {module:model/CoinChange} coin_change
 */
Operation.prototype['coin_change'] = undefined;

/**
 * @member {Object} metadata
 */
Operation.prototype['metadata'] = undefined;






export default Operation;

