/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountIdentifier from './AccountIdentifier';
import CoinIdentifier from './CoinIdentifier';
import Currency from './Currency';
import NetworkIdentifier from './NetworkIdentifier';
import Operator from './Operator';
import TransactionIdentifier from './TransactionIdentifier';

/**
 * The SearchTransactionsRequest model module.
 * @module model/SearchTransactionsRequest
 * @version 1.4.10
 */
class SearchTransactionsRequest {
    /**
     * Constructs a new <code>SearchTransactionsRequest</code>.
     * SearchTransactionsRequest is used to search for transactions matching a set of provided conditions in canonical blocks.
     * @alias module:model/SearchTransactionsRequest
     * @param networkIdentifier {module:model/NetworkIdentifier} 
     */
    constructor(networkIdentifier) { 
        
        SearchTransactionsRequest.initialize(this, networkIdentifier);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, networkIdentifier) { 
        obj['network_identifier'] = networkIdentifier;
    }

    /**
     * Constructs a <code>SearchTransactionsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchTransactionsRequest} obj Optional instance to populate.
     * @return {module:model/SearchTransactionsRequest} The populated <code>SearchTransactionsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchTransactionsRequest();

            if (data.hasOwnProperty('network_identifier')) {
                obj['network_identifier'] = NetworkIdentifier.constructFromObject(data['network_identifier']);
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = Operator.constructFromObject(data['operator']);
            }
            if (data.hasOwnProperty('max_block')) {
                obj['max_block'] = ApiClient.convertToType(data['max_block'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('transaction_identifier')) {
                obj['transaction_identifier'] = TransactionIdentifier.constructFromObject(data['transaction_identifier']);
            }
            if (data.hasOwnProperty('account_identifier')) {
                obj['account_identifier'] = AccountIdentifier.constructFromObject(data['account_identifier']);
            }
            if (data.hasOwnProperty('coin_identifier')) {
                obj['coin_identifier'] = CoinIdentifier.constructFromObject(data['coin_identifier']);
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = Currency.constructFromObject(data['currency']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/NetworkIdentifier} network_identifier
 */
SearchTransactionsRequest.prototype['network_identifier'] = undefined;

/**
 * @member {module:model/Operator} operator
 */
SearchTransactionsRequest.prototype['operator'] = undefined;

/**
 * max_block is the largest block index to consider when searching for transactions. If this field is not populated, the current block is considered the max_block. If you do not specify a max_block, it is possible a newly synced block will interfere with paginated transaction queries (as the offset could become invalid with newly added rows).
 * @member {Number} max_block
 */
SearchTransactionsRequest.prototype['max_block'] = undefined;

/**
 * offset is the offset into the query result to start returning transactions. If any search conditions are changed, the query offset will change and you must restart your search iteration.
 * @member {Number} offset
 */
SearchTransactionsRequest.prototype['offset'] = undefined;

/**
 * limit is the maximum number of transactions to return in one call. The implementation may return <= limit transactions.
 * @member {Number} limit
 */
SearchTransactionsRequest.prototype['limit'] = undefined;

/**
 * @member {module:model/TransactionIdentifier} transaction_identifier
 */
SearchTransactionsRequest.prototype['transaction_identifier'] = undefined;

/**
 * @member {module:model/AccountIdentifier} account_identifier
 */
SearchTransactionsRequest.prototype['account_identifier'] = undefined;

/**
 * @member {module:model/CoinIdentifier} coin_identifier
 */
SearchTransactionsRequest.prototype['coin_identifier'] = undefined;

/**
 * @member {module:model/Currency} currency
 */
SearchTransactionsRequest.prototype['currency'] = undefined;

/**
 * status is the network-specific operation type.
 * @member {String} status
 */
SearchTransactionsRequest.prototype['status'] = undefined;

/**
 * type is the network-specific operation type.
 * @member {String} type
 */
SearchTransactionsRequest.prototype['type'] = undefined;

/**
 * address is AccountIdentifier.Address. This is used to get all transactions related to an AccountIdentifier.Address, regardless of SubAccountIdentifier.
 * @member {String} address
 */
SearchTransactionsRequest.prototype['address'] = undefined;

/**
 * success is a synthetic condition populated by parsing network-specific operation statuses (using the mapping provided in `/network/options`).
 * @member {Boolean} success
 */
SearchTransactionsRequest.prototype['success'] = undefined;






export default SearchTransactionsRequest;

